name: mathematics
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.8+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0
  pdf: ^3.8.1
  path_provider: ^2.0.10
  syncfusion_flutter_pdfviewer: ^20.1.57-beta
  printing: ^5.9.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  universal_html: ^2.0.8
  circular_countdown_timer: ^0.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/